### ISSUE TITLE
Know more about generated url

### ISSUE THREAD

**Issue by AkibDeraiya123** [mollie/mollie-api-node#107]
Hello @vernondegoede @dabroek 

Hope you guys doing well.

I am working with mollie in node.js. It's really nice to help my system/project. Thanks for that.

But i have some questions/queries regarding some points.

I am generating payment URL using this code,
```
const moliePaymentObject = {
    amount: {
        currency: 'EUR',
        value: orderTotalAmount.toFixed(2).toString()
    },
    description: `Order for orderId:- ${orderId}`,
    redirectUrl: `redirectingUrl?order=${orderId}`,
    webhookUrl: `webhook url`,
    metadata: {
        orderID: orderID
    }
};
```

Right now i am working in testing mode.
I have few questions
1) Redirect from mollie to `redirectUrl` after webhook response i sent to mollie?
2) What response i need to send to mollie webhook request?
3) Right now i am sending only `200` response code of webhook request(`Using res.status(200)`). Once i sent a response to mollie webhook request 200 then mollie is redirect user to redirectUrl. After sometime i see mollie is again call the same webhookURL whatever i set at the time of generate payment URL. Why it's called another time? Actually when mollie is called my webhook URL i am attaching transactionId to with my orderId record. Now when again it will called it will change my record(I know transactionId is always same for same webhook). But i want to prevent this multiple times same webhook url calling to my system. How can i?
4) How can i manage redirection to user after payment success and failed/canceled status to my website?

**Comment by martinmollie** [comment]
Hi @AkibDeraiya123,

1. Correct! We redirect the consumer to the `redirectUrl` after we've received the `200 OK` status from you.
2. Just the `200 OK` status. We describe this in step 4 of our payments overview guide: https://docs.mollie.com/payments/overview
3. I don't fully understand this question but we call your webhook whenever the status of a payment changes. This could be multiple times, so that would explain the multiple webhook calls. We can't stop these webhook calls from happening, but you should be able to build a check that will prevent your side from doing anything after the first webhook call. Let me know if this answers your question or not!
4. You can only pass a single `redirectUrl` when creating a payment. Most developers add a unique identifier to this URL (like the order ID) so you can show the right page referencing the order when the customer returns. Because we call your webhook before we send the customer off to the `redirectUrl`, you should know if the payment was successful or not. This way you can show the appropriate page.
