### ISSUE TITLE
Can't create a Payment object

### ISSUE THREAD

**Issue by Christilut** [mollie/mollie-api-node#127]
Hi,

I'm trying to create a Payment object manually for testing purposes (webhooks is kind of a hard thing to use during tests) but I keep getting this error:

```
import { Payment } from '@mollie/api-client'

const payment = new Payment(paymentObject) // Payment object is parsed JSON saved from earlier
```

```
api_client_1.Payment is not a constructor
```

Now I'm not sure if this is because of something the library does or my TypeScript config, but I can't figure out why this doesn't work.

Any ideas?

**Comment by Pimm** [comment]
Hi Christiaan,

Typically, you would create a Payment object by calling `mollieClient.payments.create`. `Payment` is exported not for you to construct your own instances; but rather to allow you to use it as a type in your code. However, you mentioned that it was for testing purposes, and tests are often atypical.

Could you explain what you are trying to achieve?

You can make calls using a test API key, which I assume you are already doing. You can mock out Mollie's backend completely by passing an adapter to `createMollieClient`. If you are merely testing your own code rather than the integration, you could mock out the internals of this library.

**Comment by Christilut** [comment]
Hi,

I'm using like normally in my tests (with test key), someone on github here mentioned that that is normal for testing and the test data gets deleted after a few weeks anyway.

But I can't mock the `await MollieClient.payments.get(transactionId)` call since that requires that payment being paid by a user. I didn't find any way to mark a payment paid manually.
I wanted to create the `Payment` object manually because my code relies on it's methods, eg `isPaid()'.

I didn't know about the adapter, I'll see if that fits my needs. If that can simply return a JSON that I already saved earlier then it's totally fine.

**Comment by Pimm** [comment]
You could indeed record the response returned by Mollie's backend, save that, and then use an adapter to inject that response in your tests to simulate a user completing the payment.

I might personally instead just inject a mock Payment object whose `isPaid` method always returns `true`.

It depends on whether you are trying to test the complete integration, or just the code which handles your customers paying a payment.

**Comment by vernondegoede** [comment]
> someone on github here mentioned that that is normal for testing and the test data gets deleted after a few weeks anyway.

Test payments are no longer cleaned up, but I agree with @Pimm  it's indeed better to mock the Payment object instead of relying on external calls in your tests.

**Comment by Christilut** [comment]
Okay, I'll mock everything then, I think that's the best method anyway. Thanks!
