### ISSUE TITLE
Build error in react-native

### ISSUE THREAD

**Issue by RAJESHKUMAR21TL** [mollie/mollie-api-node#134]
error: bundling failed: Error: Unable to resolve module `path` from `node_modules/@mollie/api-client/dist/mollie.cjs.js`: path could not be found within the project.

If you are sure the module exists, try these steps:
 1. Clear watchman watches: watchman watch-del-all
 2. Delete node_modules: rm -rf node_modules and run yarn install
 3. Reset Metro's cache: yarn start --reset-cache
 4. Remove the cache: rm -rf /tmp/metro-*

I followed the above steps to resolve. But not helped me

**Comment by vernondegoede** [comment]
Hi @RAJESHKUMAR21TL,

Modules that depend on native Node modules cannot be used within React Native, as they are written in C++, not JavaScript. An example module that we depend on is the `path` module.

**Comment by RAJESHKUMAR21TL** [comment]
Thank you. @vernondegoede . Any work around or suggestion do you have?

**Comment by Pimm** [comment]
Hi!

Your architecture is the underlying issue.

You should not use this library in your RN app. Instead, you should set up a Node.js server. This server will include this library. From your RN app, rather than calling `mollieClient.payments.create` directly, you'll make a request to your server and your server will in turn call `mollieClient.payments.create`.

This will clear up that error as well, since you won't be using this library in your RN app.

Alternatively, you can set up a PHP, Ruby, or Python server instead of a Node.js one.
