### ISSUE TITLE
Error: * fs in ./node_modules/@mollie/api-client/dist/mollie.esm.js

### ISSUE THREAD

**Issue by bbeemster** [mollie/mollie-api-node#152]
Hi,

I'm using a Gatsby/React setup. I've added the `@mollie/api-client` package to my project and added the following code on the client side: 

```
import createMollieClient from '@mollie/api-client';

const mollieClient = createMollieClient({ apiKey: 'test_dHar4XY7LxsDOtmnkVtjNVWXLSlXsM' });
```

I now get the following error:

`This dependency was not found:`
`* fs in ./node_modules/@mollie/api-client/dist/mollie.esm.js`

Any clue what this is and how I can fix it? I tried adding `fs` both to my project and to the `@mollie/api-client` inside the node_modules folder.

**Comment by Pimm** [comment]
Hi Bart,

Are you using `@mollie/api-client` inside your Gatsby/React-app?

**Comment by bbeemster** [comment]
HI @Pimm,

Yes I am

**Comment by Pimm** [comment]
Thank you for the response.

Although this version of the library is written in JavaScript, it is still designed to run on a server (in Node.js to be specific).

This is not a shortcoming: it is by design. You will have to set up a Node.js server which runs this library, or alternatively run a PHP, Ruby, or Python server.

[See this issue](https://github.com/mollie/mollie-api-node/issues/130#issuecomment-587379937) for more information.

I see now that this is not obvious. We should be more vocal about this. Thank you for bringing this to my attention.

**Comment by bbeemster** [comment]
@Pimm Thanks for your quick response. I thought the payment needed to be created on the client side. Thanks again!
