### ISSUE TITLE
Vulnerability in axios

### ISSUE THREAD

**Issue by amir-secondcompany** [mollie/mollie-api-node#190]
When running `npm audit`, projects that have `@mollie/api-client` installed report issue with axios library. Can the specified package be updated? 

<img width="651" alt="image" src="https://user-images.githubusercontent.com/45872763/105045125-d4028b80-5a67-11eb-9ccd-6333561a3567.png">

Information about the issue:  https://npmjs.com/advisories/1594

**Comment by Pimm** [comment]
Hi, thanks for opening this issue. As was [previously discussed in #187](https://github.com/mollie/mollie-api-node/pull/187), the security issue in axios is not one which realistically affects Mollie merchants.

The dependency will be updated in the near future. However ‒ as there is no security risk ‒ this will happen in the next planned release instead of a hotfix.

**Comment by Pimm** [comment]
The latest version of the library uses a newer axios. If anyone is still concerned about this, upgrade to 3.5.0+.
