### ISSUE TITLE
the current version of axios dependency used in v3.4.0 has SSRF vulnerability

### ISSUE THREAD

**Issue by feyyazesat** [mollie/mollie-api-node#191]
When I use `@mollie/api-client: 3.4.0` as a dependency in my project, npm audit shows the following output. The current used axios version is 0.19.0

<img width="581" alt="Screenshot 2021-01-21 at 09 50 10" src="https://user-images.githubusercontent.com/1338800/105327169-dd5a3800-5bce-11eb-9cee-12ff969b815d.png">

**Comment by Pimm** [comment]
Hi, thanks for opening this issue. As was [previously discussed in #187](https://github.com/mollie/mollie-api-node/pull/187), the security issue in axios is not one which realistically affects Mollie merchants.

The dependency will be updated in the near future. However ‒ as there is no security risk ‒ this will happen in the next planned release instead of a hotfix.

Of course you could force the dependency to be resolved to a later version in your setup, or use the current `master` branch of this library, if you really wanted to.

**Comment by Pimm** [comment]
The latest version of the library uses a newer axios. If anyone is still concerned about this, upgrade to 3.5.0+.
