### ISSUE TITLE
Axios security vulnerability

### ISSUE THREAD

**Issue by timmakken** [mollie/mollie-api-node#194]
Hi,

I'm working on implementing the mollie api client into my backend but the npm audit returned some concerns.
there is a high risk vulnerability found on the dependency axios in the mollie client that needs to be updated to 0.21.1 where Axios fixed the issue.

Could you please update this dependency and publish a new version of the node client.

Kind regards,
Tim

**Comment by Pimm** [comment]
Hi Tim, thanks for opening this issue. As was [previously discussed in #187](https://github.com/mollie/mollie-api-node/pull/187), the security issue in axios is not one which realistically affects Mollie merchants.

The dependency will be updated in the near future (likely this week). However ‒ as there is no security risk ‒ this will happen in the next planned release instead of a hotfix.

Of course you could force the dependency to be resolved to a later version in your setup, or use the current `master` branch of this library, if you really wanted to.

**Comment by Pimm** [comment]
The latest version of the library uses a newer axios. If anyone is still concerned about this, upgrade to 3.5.0+.
