### ISSUE TITLE
Subscription amount limit

### ISSUE THREAD

**Issue by stephanoshadjipetrou** [mollie/mollie-api-node#277]
Hi I'm trying to create a subscription and noticed that when setting the `amount.value` higher than 1000.00 it throws this error
```
{
    "status": 422,
    "title": "Unprocessable Entity",
    "detail": "The amount is higher than the maximum",
    "field": "amount",
    "_links": {
        "documentation": {
            "href": "https://docs.mollie.com/overview/handling-errors",
            "type": "text/html"
        }
    }
}
```
Is there a way to increase the amount limit?

**Comment by Pimm** [comment]
Hi Stefanos,

There are ‒ indeed ‒ [maximum amounts per payment method](https://help.mollie.com/hc/en-us/articles/115000667365-Wat-is-het-minimum-en-maximumbedrag-per-betaalmethode-). Whether those can be increased is [a question for support](https://www.mollie.com/contact/merchants).

**Comment by Pimm** [comment]
When a customer subscribes through iDEAL, subsequent payments (after the first one) use SEPA Direct Debit as their method. This is because iDEAL requires user interaction. So it makes sense for the maximum for such a subscription to be the smallest out of the iDEAL maximum and the SEPA Direct Debit maximum.

However, this is very much [a question for support](https://www.mollie.com/contact/merchants). It is outside the scope of the Node.js client, and therefore not something with which I can help you adequately.
