### ISSUE TITLE
Opening up the internals of this API

### ISSUE THREAD

**Issue by edorivai** [mollie/mollie-api-node#67]
I initially started writing an issue asking whether the [Settlement API](https://docs.mollie.com/reference/v2/settlements-api/get-settlement) would be supported any time soon. 

Then, while looking through the code, I realized it should be relatively straightforward to implement my own `resources`. However, this library is only exporting the `mollie` wrapper, without exporting the internals that would allow for easily implementing resources myself (like the `httpClient`, base `resource` etc).

Would you guys be open to opening up the internals? I'm actually scratching my head a little around the decision to run this library through rollup, as it's a node specific library in the first place.

**Comment by dabroek** [comment]
Hi @edorivai! 

First of all, thank you for your interest in our node client! We just released the V2 of this client supporting the V2 of our API (enabling you to use multicurrency).

The Settlement endpoint you are referring to does require a little different approach since it is using an OAuth mechanism to authenticate. Unfortunately this package does not offer a way to properly utilise this flow just yet.

We would love for you to contribute to this package by opening a PR to add support more of our APIs. Any help would be greatly appreciated, not only by us, but also by the rest of the community. 

Hope to see your contributions in the near future!

**Comment by edorivai** [comment]
Hey, thanks for the response!

I indeed bumped into the OAuth thing, and implemented a custom settlement coupling. I don't have enough experience with the internals of this API to feel comfortable to come up with how OAuth should be supported though. Are there any plans of adding the OAuth-based parts of the API on your end?

**Comment by vernondegoede** [comment]
@edorivai The OAuth-based parts (Mollie Connect) will be supported by this Node client in the future. Unfortunately, I can't give you any ETA. 

We'll update this ticket once we know more 👍
