### ISSUE TITLE
Semantic versioning

### ISSUE THREAD

**Issue by joepie91** [mollie/mollie-api-node#9]
Given the instructions to add `>= 1.0.x` to package.json (and the absence of a `--save` flag in the `npm install` command), it seems that this module doesn't follow [semantic versioning](https://gist.github.com/joepie91/9b9dbd8c9ac3b55a65b2#semantic-versioning).

To ensure reliable operation and safe upgrades, however, this would be a necessity (expanded upon further at the link above).

**Comment by RicardoJ** [comment]
Hello Sven,

First of all, I'd like to apologize that you got no response from us since your issue has been created. I'll look into the semantic versioning for this api client and will referer any pull requests with this issue number.

Feel free to add any more information, if necessary. Thank you for your input so far. We really appreciate it.

Ricardo,
[Mollie](https://www.mollie.com)
